const DATA_OBJECT_BASE_KEY = ["timelineObjects"];
const FIELD_THAT_HAS_TRAVEL_DATA = ["activitySegment"];
const START_LOCATION_OBJECT_NAME = ["startLocation"];
const END_LOCATION_OBJECT_NAME = ["endLocation"];
const START_LOCATION_FIELD_NAME = ["latitudeE7"];
const END_LOCATION_FIELD_NAME = ["longitudeE7"];
const TIME_OBJECT_NAME = ["duration"];
const START_TIME_FIELD_NAME = ["startTimestampMs"];
const END_TIME_FIELD_NAME = ["endTimestampMs"];
const MODE_OF_TRANSPORT_OBJECT_NAME = ["activityType"];
const DISTANCE_OBJECT_NAME = ["distance"];
const INPUT_FILE_TYPES = ".json";
const LOCATION_LAT_LAN_DIVIDE_FACTOR = 10000000;

export {
  DATA_OBJECT_BASE_KEY,
  FIELD_THAT_HAS_TRAVEL_DATA,
  START_LOCATION_OBJECT_NAME,
  END_LOCATION_OBJECT_NAME,
  START_LOCATION_FIELD_NAME,
  END_LOCATION_FIELD_NAME,
  TIME_OBJECT_NAME,
  START_TIME_FIELD_NAME,
  END_TIME_FIELD_NAME,
  MODE_OF_TRANSPORT_OBJECT_NAME,
  DISTANCE_OBJECT_NAME,
  INPUT_FILE_TYPES,
  LOCATION_LAT_LAN_DIVIDE_FACTOR,
};
